name: Build Docker Image
on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
      folder:
        required: true
        type: string
    secrets:
      packages_token:
        required: true

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.folder }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          tags: ${{ inputs.docker_tag }}
          context: ${{ inputs.folder }}
          build-args: |
            NODE_ENV=production
            GIT_COMMIT=${{ github.sha }}
            UID=1001
            GID=1001
            USER=superman
            GROUP=superman
          secrets: |
            github_packages_token=${{ secrets.packages_token }}
